suppressMessages(library(tidyr))
suppressMessages(library(dplyr))
suppressMessages(library(lubridate))
suppressMessages(library(maptools))
suppressMessages(library(rgeos))
suppressMessages(library(rgdal))
suppressMessages(library(spatial))
suppressMessages(library(here))
suppressMessages(library(sf))
suppressMessages(library(tibble))
suppressMessages(library(readxl))
suppressMessages(library(ggplot2))
suppressMessages(library(raster))
suppressMessages(library(sp))
suppressMessages(library(inlabru))
suppressMessages(library(ggpubr))
suppressMessages(library(renv))
library(readr)
library(ggridges)
library(plot3D)
library(ggrgl)
library(tidyverse)
library(ggrepel)
library(ggtext)
library(showtext)
library(readxl)
font_add_google("Lato")
showtext_auto()

# Libraries

library(hrbrthemes)
library(viridis)


sal<-read_xlsx("Data/ChinookEscape_1960_2020.xlsx")
